# Jekyll configuration for cerebrate-file documentation
# this_file: docs/_config.yml

# Theme
remote_theme: just-the-docs/just-the-docs

# Site settings
title: Cerebrate File Documentation
description: Process large documents with Cerebras AI by intelligent chunking and context preservation
baseurl: "/cerebrate-file"
url: "https://twardoch.github.io"

# Just the Docs theme configuration
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Enable copy button on code blocks
enable_copy_code_button: true

# Footer
footer_content: "Copyright &copy; 2024-2025 Adam Twardoch. Distributed under the Apache 2.0 license."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Navigation
nav_enabled: true
nav_sort: case_sensitive
back_to_top: true
back_to_top_text: "Back to top"

# External links
aux_links:
  "GitHub Repository":
    - "https://github.com/twardoch/cerebrate-file"
  "PyPI Package":
    - "https://pypi.org/project/cerebrate-file/"
  "Cerebras AI":
    - "https://cerebras.ai"

# Collections for organizing documentation
collections:
  examples:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      nav_enabled: true
  - scope:
      path: "_examples"
      type: "examples"
    values:
      layout: "default"
      nav_enabled: false
  - scope:
      path: "_tutorials"
      type: "tutorials"
    values:
      layout: "default"
      nav_enabled: false

# Plugins
plugins:
  - jekyll-seo-tag

# Exclude files from Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - "*.gemspec"
  - "*.gem"
  - .idea/
  - .vscode/

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Google Analytics (optional - replace with your tracking ID)
# ga_tracking: UA-XXXXXXXXX-X

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false